spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
