### Test createSample method in SampleController
### See: src/main/java/org/skwzz/presentation/SampleController.java
POST http://localhost:8080/api/sample
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0VXNlciIsImlhdCI6MTcyNTQzNTM3OSwiZXhwIjoxNzI1NDM1NDA5fQ.WTelO_gF9eXLIJcUPPnpOvyP3C3pr52WKd8wThDNeE0
